export const site = {
  name: "Shubh Gupta",
  handle: "shubhxho",
  title: "Shubh Gupta (shubhxho) — Engineer, Hacker & Builder",
  shortTitle: "Shubh Gupta — shubhxho",
  description:
    "Shubh Gupta, known online as shubhxho, is an engineer and hacker from Khagaria, India building robotics, AI, developer tools, and systems software.",
  bio: "I build robots, AI systems, developer tools, and unusual software from Khagaria, India.",
  url: "https://shubhxho.com",
  mark: "shubh.",
  monogram: "s/x",
  timezone: "Asia/Kolkata",
  timeLabel: "Shubh Time",
  copyrightName: "Shubh Gupta",
  locale: "en_US",
  language: "en-IN",
  lastUpdated: "2026-08-26",
  email: "shubh@shubhxho.com",
  keywords: [
    "Shubh Gupta",
    "shubhxho",
    "Shubh Gupta shubhxho",
    "engineer from Khagaria",
    "robotics engineer",
    "AI engineer",
    "systems software",
    "developer tools",
    "HFT",
    "Hudson River Trading",
    "Khagaria",
    "India",
  ],
  topics: [
    "Robotics",
    "Artificial intelligence",
    "Systems software",
    "Developer tools",
    "High-frequency trading",
    "Rust",
    "Go",
    "Linux",
  ],
  links: {
    x: "https://x.com/shubhgupta",
    in: "https://www.linkedin.com/in/shubhxho",
    ig: "https://www.instagram.com/shubhxho",
    gh: "https://github.com/shubhxho",
    hf: "https://huggingface.co/shubhxho",
    kg: "https://www.kaggle.com/shubhxho",
  },
} as const;
